field: 1c27a358-8a8c-4336-80f4-01ed8eb2015a # Content Builder
fieldLayouts:
  14ea5679-7880-4a30-a55a-3f82647b5c2c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8647721a-dcfd-44e1-b957-645948b6e71e # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 228df430-d74e-468e-8f57-946abf985ea9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30d0e068-6a99-4cc9-a11d-c725154aca86
        userCondition: null
fields:
  8647721a-dcfd-44e1-b957-645948b6e71e: # Text
    columnSuffix: kmvdcfvl
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: 1
