fieldLayouts:
  e170d7fe-6d90-4eee-a72b-d0393b3e6aae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Add a title'
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b773c16d-5499-4188-b077-3f67d27b2f39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6865af4-d8a1-4b40-b06a-9d1bc210f7c3 # Rich Text
            instructions: null
            label: 'About Page Copy'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2a15f67-e987-45a9-8a8d-8c6f65838181
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 46334d0c-c117-4fde-874d-861508ce0394
        userCondition: null
handle: about
hasTitleField: true
name: About
section: 7aca40ff-a30b-405f-9c6f-93f6942f6a0f # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
