fieldLayouts:
  2043d001-d749-4d40-b327-2740f15cc0f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4e669cd-cc04-4ca8-86fd-72631c5409c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d5b78de-9b65-4f09-9c55-a01e3acbbfea # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf4525b0-6f15-419b-a844-e00ea2eb52d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2c1c5c4-cc3a-4b6d-83f2-1d068f270092 # Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d343c96-fea9-4d56-82ab-deda8de8f875
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 51d4872e-5094-497b-b2a6-be7315e05cba
            userCondition: null
          -
            elementCondition: null
            fieldUid: 1c27a358-8a8c-4336-80f4-01ed8eb2015a # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22270e1c-31cc-43c5-889f-bcc75b3cab1b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 92be8856-d785-409c-a017-588d80cf089b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 745943b4-ec0e-46cb-920f-dbf5d7f7f123 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bec8a2b-7ea3-4fc0-a0e5-d19cb8292d09
            userCondition: null
            warning: null
            width: 100
        name: Images
        uid: 63c59811-16a9-470f-932d-a04198488231
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: ac27abc7-b338-40f4-94f7-ac5913e23a79 # Adventures
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
